![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [73]:
import numpy as np

# **Arithmetic operations**
Tất cả các toán tử số học thông thường (+, -, * , /, //, ** , etc.) đều có thể sử dụng được với **ndarrays**

Các phép toán dưới đây vận hành trên mảng cùng hình dạng, mỗi phần tử mảng này sẽ thực hiện phép toán với phần tử tương ứng mảng kia

In [74]:
a = np.array([14, 23, 32, 41])
b = np.array([5, 4, 3, 2])

In [75]:
print("a + b =", a + b)

a + b = [19 27 35 43]


In [76]:
print("a - b =", a - b)

a - b = [ 9 19 29 39]


In [77]:
print("a * b =", a * b)

a * b = [70 92 96 82]


In [78]:
print("a / b =", a / b)

a / b = [ 2.8         5.75       10.66666667 20.5       ]


In [79]:
print("a // b =", a // b)

a // b = [ 2  5 10 20]


In [80]:
print("a % b =", a % b)

a % b = [4 3 2 1]


In [81]:
print("a ** b =", a ** b)

a ** b = [537824 279841  32768   1681]


Các mảng phải có hình dạng giống nhau. Nếu không, **NumPy** sẽ áp dụng các quy tắc **Broadcasting**

# **Broadcasting**
Tổng quát, khi các mảng không cùng hình dạng, **Numpy** sẽ áp dụng quy tắc **Broadcasting**

### **First rule**
Nếu các mảng không có cùng **rank**, thì 1 sẽ được thêm vào trước các mảng xếp hạng nhỏ hơn cho đến khi xếp hạng của chúng khớp với nhau.

In [82]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
arr = arr.reshape(1, 1, 10)
arr

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

Thử cộng mảng 1D với mảng **arr** (3D)

In [84]:
arr + np.arange(0, 100, 10)

array([[[ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99]]])

### **Second rule**

In [85]:
arr2 = np.arange(9).reshape(3, 3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
arr2 + [[100], [200], [300]]

array([[100, 101, 102],
       [203, 204, 205],
       [306, 307, 308]])

Áp dụng **First rule** và **Second rule**

In [87]:
arr2 + [1000, 2000, 3000]

array([[1000, 2001, 3002],
       [1003, 2004, 3005],
       [1006, 2007, 3008]])

In [88]:
arr2 + 500

array([[500, 501, 502],
       [503, 504, 505],
       [506, 507, 508]])

### **Upcasting**
Khi cố gắng kết hợp các mảng với các kiểu **dtypes** khác nhau, **NumPy** sẽ **upcast** một kiểu có khả năng xử lý tất cả các giá trị có thể có

In [89]:
k1 = np.arange(-3, 8, dtype=np.int8)
k1

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7], dtype=int8)

In [90]:
k2 = k1 + np.arange(0, 11, dtype=np.uint8)
k2

array([-3, -1,  1,  3,  5,  7,  9, 11, 13, 15, 17], dtype=int16)

In [91]:
k3 = k1 + 1.5
print(k3, k3.dtype)

[-1.5 -0.5  0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5] float64
